import { ChevronRight, CircleAlert, FileCheck2, Gauge, ShieldCheck, Sparkles, UserRound, X } from 'lucide-react';
import type { Project } from '../../types/project';
import { RiskBadge } from '../../components/RiskBadge';
import { PredictionCard } from '../../components/PredictionCard';
import { ProgressTimeline } from '../../components/ProgressTimeline';
import { RiskFactorList } from '../../components/RiskFactorList';
import { RecommendationCard } from '../../components/RecommendationCard';
import { PanelHeader } from '../../components/PanelHeader';
import { useRecommendations } from '../../hooks/useRecommendations';

export function ProjectDetailDrawer({ project, onClose, onToast }: { project: Project; onClose: () => void; onToast: (message: string) => void }) { return <div className="detail-overlay"><aside className="detail-drawer" data-demo="project-detail"><div className="detail-head"><div><span className="eyebrow">PROJECT DETAIL</span><h2>{project.name}</h2><p>{project.id} · {project.district}, {project.state}</p></div><button className="icon-button" onClick={onClose} aria-label="Close detail"><X size={19} /></button></div><div className="detail-scroll"><div className="detail-status"><RiskBadge risk={project.risk} /><span className="status-copy"><span>Current stage</span><strong>{project.stage}</strong></span><span className="status-copy"><span>Last updated</span><strong>{project.updated}</strong></span></div><PredictionCard project={project} /><div className="why-card" data-demo="why-card"><div className="why-title"><div className="why-icon"><Sparkles size={17} /></div><div><h3>Why is this project at risk?</h3><span>Explainable AI · Model v2.4 · 89% confidence</span></div></div><p className="association-note">These factors are associated with higher predicted delay risk. They are not causal findings.</p><RiskFactorList factors={[{ color: 'red', title: project.factor, detail: 'Current value is materially above the district baseline.', value: '+31%' }, { color: 'red', title: `${project.objections} unresolved landowner objections`, detail: 'Objection review remains the active bottleneck.', value: '+22%' }, { color: 'yellow', title: 'Compensation approval queue ageing', detail: project.compensation, value: '+14%' }, { color: 'green', title: 'Document verification is progressing', detail: 'Verified documents reduce downstream uncertainty.', value: '−8%' }]} /></div><RecommendedActions project={project} onToast={onToast} /><div className="timeline-card"><PanelHeader title="Acquisition timeline" meta="6 stages · 4 completed" /><ProgressTimeline currentStage={project.stage} /></div><div className="detail-sections"><button><FileCheck2 size={16} />Documents <span>12 / 16 verified</span><ChevronRight size={15} /></button><button><UserRound size={16} />Landowners & objections <span>{project.owners} owners · {project.objections} open</span><ChevronRight size={15} /></button><button><Gauge size={16} />Compensation <span>{project.compensation}</span><ChevronRight size={15} /></button><button><ShieldCheck size={16} />Legal issues <span>{project.legal}</span><ChevronRight size={15} /></button></div></div></aside></div>; }

/**
 * Ranked actions from the recommendation engine. Each card shows the evidence
 * the action rests on, so an officer can check it against the case record.
 */
function RecommendedActions({ project, onToast }: { project: Project; onToast: (message: string) => void }) {
  const { data, isLoading } = useRecommendations(project);
  const items = data?.items ?? [];
  return <div className="action-card" data-demo="recommended-actions"><div className="action-title"><div className="action-icon"><CircleAlert size={17} /></div><div><h3>What should the officer do?</h3><span>{isLoading ? 'Loading ranked actions' : `${items.length} action(s) ranked by evidence, model linkage, urgency, and policy weight`}</span></div></div><p className="association-note">Each action is generated from a measured value on this case. An action may reduce a bottleneck; it is not a guaranteed schedule outcome, and an authorized official decides whether to act.{data && !data.live ? ' Showing demo data derived from this project record; the API is unavailable.' : ''}</p>{isLoading ? <p className="muted">Loading recommendations…</p> : items.length === 0 ? <p className="muted">No material bottleneck is recorded against this project at present.</p> : items.map((recommendation) => <RecommendationCard key={recommendation.recommendationId} recommendation={recommendation} onAssign={() => onToast(`${recommendation.action.slice(0, 60)}… assigned to ${recommendation.responsibleDepartment}`)} />)}</div>;
}
