/**
 * Demonstration dataset.
 *
 * Twenty-three land acquisition cases drawn from the situations these projects
 * actually get stuck in: clean corridors through public land, cases where the
 * paperwork has drifted, cases where compensation has aged past the point of
 * goodwill, and cases sitting under a court order.
 *
 * **Risk is derived, never asserted.** Each case records measured facts, and the
 * rule engine scores them. `expectedRisk` below is what the authors believe the
 * facts describe; a test runs the engine and fails if the two disagree. Changing
 * a project's risk means changing its facts, which is the point: a demo where
 * the labels were typed in teaches the audience nothing about the system.
 *
 * Money is in rupees, area in hectares, and the stage names follow the Right to
 * Fair Compensation and Transparency in Land Acquisition, Rehabilitation and
 * Resettlement Act, 2013.
 */

import type { ProjectMetrics } from '../src/recommendations/types.js';

export type RiskBand = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/** How a case has moved over the last six months, for the trend chart. */
export type Trajectory = 'IMPROVING' | 'STABLE' | 'WORSENING' | 'SPIKING';

export type DemoMilestone = {
  name: string;
  /** Days from the snapshot date. Negative is in the past. */
  plannedIn: number;
  status: 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'OVERDUE' | 'CANCELLED';
  ownerDept?: string;
  completedIn?: number;
};

export type DemoDocument = {
  documentType:
    | 'TITLE_DEED'
    | 'MUTATION_RECORD'
    | 'SURVEY_PLAN'
    | 'ENCUMBRANCE_CERTIFICATE'
    | 'OBJECTION_FILING'
    | 'HEARING_ORDER'
    | 'AWARD_STATEMENT'
    | 'COMPENSATION_VOUCHER'
    | 'PAYMENT_PROOF'
    | 'POSSESSION_CERTIFICATE'
    | 'LEGAL_NOTICE'
    | 'COURT_ORDER'
    | 'IDENTITY_PROOF'
    | 'OTHER';
  status: 'REQUIRED' | 'SUBMITTED' | 'VERIFIED' | 'REJECTED' | 'EXPIRED';
  count: number;
};

export type DemoProject = {
  projectCode: string;
  name: string;
  state: string;
  district: string;
  department: string;
  projectType: string;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  status: 'DRAFT' | 'ACTIVE' | 'ON_HOLD' | 'COMPLETED' | 'CANCELLED';
  /** Days from the snapshot date; negative is in the past. */
  startedIn: number;
  targetIn: number;
  areaHectares: number;
  /** The stage the case is in, shown on the dashboard. */
  stage: string;
  /** What this case is meant to demonstrate. Shown in the walkthrough. */
  scenario: string;
  /** What the authors believe the facts describe. A test verifies it. */
  expectedRisk: RiskBand;
  trajectory: Trajectory;
  metrics: ProjectMetrics;
  milestones: DemoMilestone[];
  documents: DemoDocument[];
};

const PWD = 'Public Works Department';
const NHAI = 'National Highways Authority';
const WATER = 'Water Resources';
const URBAN = 'Urban Development';
const RAIL = 'Railways';
const POWER = 'Energy and Power';
const INDUSTRY = 'Industrial Development';
const LAND_CELL = 'Land Acquisition Cell';

// --- Low risk ---------------------------------------------------------------
// Clean cases. Documents complete, objections proportionate to the number of
// landowners, schedule holding. These exist so the dashboard has a baseline;
// a demo where everything is on fire shows nothing about discrimination.

const LOW_RISK: DemoProject[] = [
  {
    projectCode: 'KA-BLR-2026-014',
    name: 'Bengaluru Peripheral Ring Road Package 4',
    state: 'Karnataka',
    district: 'Bengaluru Rural',
    department: NHAI,
    projectType: 'EXPRESSWAY',
    priority: 'HIGH',
    status: 'ACTIVE',
    startedIn: -420,
    targetIn: 180,
    areaHectares: 1_284.6,
    stage: 'Compensation disbursement',
    scenario:
      'A large expressway package with 1,240 affected landowners and only 11 unresolved objections. Documents are complete and compensation is moving. Scale alone does not make a case risky.',
    expectedRisk: 'LOW',
    trajectory: 'IMPROVING',
    metrics: {
      parcelCount: 892,
      affectedLandownerCount: 1_240,
      unresolvedRecordCount: 4,
      objectionCount: 96,
      unresolvedObjectionCount: 11,
      requiredDocumentCount: 148,
      missingDocumentCount: 2,
      invalidDocumentCount: 0,
      documentVerificationPendingCount: 5,
      pendingApprovalCount: 1,
      blockedDependencyCount: 0,
      pendingCompensationAmount: 412_000_000,
      paymentProcessingDays: 18,
      openLegalCaseCount: 0,
      daysInCurrentStage: 34,
      averageStageDurationDays: 62,
      milestoneSlippageCount: 0,
      daysSinceLastUpdate: 2,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -400, status: 'COMPLETED', completedIn: -398, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -320, status: 'COMPLETED', completedIn: -316, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -210, status: 'COMPLETED', completedIn: -205, ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: -120, status: 'COMPLETED', completedIn: -118, ownerDept: LAND_CELL },
      { name: 'Section 23 award preparation', plannedIn: -40, status: 'COMPLETED', completedIn: -38, ownerDept: 'Revenue Department' },
      { name: 'Compensation disbursement', plannedIn: 45, status: 'IN_PROGRESS', ownerDept: 'Finance and Compensation Department' },
      { name: 'Possession and handover', plannedIn: 150, status: 'PENDING', ownerDept: NHAI },
    ],
    documents: [
      { documentType: 'TITLE_DEED', status: 'VERIFIED', count: 42 },
      { documentType: 'SURVEY_PLAN', status: 'VERIFIED', count: 18 },
      { documentType: 'AWARD_STATEMENT', status: 'VERIFIED', count: 12 },
      { documentType: 'COMPENSATION_VOUCHER', status: 'SUBMITTED', count: 5 },
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 2 },
    ],
  },
  {
    projectCode: 'KL-EKM-2026-007',
    name: 'Kochi Water Supply Augmentation Main',
    state: 'Kerala',
    district: 'Ernakulam',
    department: WATER,
    projectType: 'WATER_SUPPLY',
    priority: 'MEDIUM',
    status: 'ACTIVE',
    startedIn: -260,
    targetIn: 210,
    areaHectares: 48.2,
    stage: 'Section 19 declaration',
    scenario:
      'A narrow pipeline corridor through mostly government land. Twenty-nine landowners, three objections, nothing outstanding. The straightforward case an officer should not have to think about.',
    expectedRisk: 'LOW',
    trajectory: 'STABLE',
    metrics: {
      parcelCount: 31,
      affectedLandownerCount: 29,
      unresolvedRecordCount: 1,
      objectionCount: 5,
      unresolvedObjectionCount: 3,
      requiredDocumentCount: 24,
      missingDocumentCount: 1,
      invalidDocumentCount: 0,
      documentVerificationPendingCount: 2,
      pendingApprovalCount: 1,
      blockedDependencyCount: 0,
      pendingCompensationAmount: 24_600_000,
      paymentProcessingDays: 12,
      openLegalCaseCount: 0,
      daysInCurrentStage: 26,
      averageStageDurationDays: 45,
      milestoneSlippageCount: 0,
      daysSinceLastUpdate: 1,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -240, status: 'COMPLETED', completedIn: -239, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -180, status: 'COMPLETED', completedIn: -176, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -90, status: 'COMPLETED', completedIn: -88, ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: 30, status: 'IN_PROGRESS', ownerDept: LAND_CELL },
      { name: 'Section 23 award preparation', plannedIn: 110, status: 'PENDING', ownerDept: 'Revenue Department' },
      { name: 'Compensation disbursement', plannedIn: 175, status: 'PENDING', ownerDept: 'Finance and Compensation Department' },
    ],
    documents: [
      { documentType: 'TITLE_DEED', status: 'VERIFIED', count: 14 },
      { documentType: 'SURVEY_PLAN', status: 'VERIFIED', count: 6 },
      { documentType: 'ENCUMBRANCE_CERTIFICATE', status: 'SUBMITTED', count: 2 },
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 1 },
    ],
  },
  {
    projectCode: 'MH-NSK-2026-022',
    name: 'Nashik Solar Park Transmission Corridor',
    state: 'Maharashtra',
    district: 'Nashik',
    department: POWER,
    projectType: 'POWER_TRANSMISSION',
    priority: 'MEDIUM',
    status: 'ACTIVE',
    startedIn: -190,
    targetIn: 240,
    areaHectares: 96.4,
    stage: 'Survey and demarcation',
    scenario:
      'A transmission line taking narrow tower footprints rather than continuous land. Few owners per kilometre, no disputes, early in its schedule.',
    expectedRisk: 'LOW',
    trajectory: 'STABLE',
    metrics: {
      parcelCount: 58,
      affectedLandownerCount: 64,
      unresolvedRecordCount: 2,
      objectionCount: 7,
      unresolvedObjectionCount: 4,
      requiredDocumentCount: 36,
      missingDocumentCount: 2,
      invalidDocumentCount: 0,
      documentVerificationPendingCount: 3,
      pendingApprovalCount: 1,
      blockedDependencyCount: 0,
      pendingCompensationAmount: 38_200_000,
      paymentProcessingDays: 9,
      openLegalCaseCount: 0,
      daysInCurrentStage: 41,
      averageStageDurationDays: 55,
      milestoneSlippageCount: 0,
      daysSinceLastUpdate: 3,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -170, status: 'COMPLETED', completedIn: -168, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: 20, status: 'IN_PROGRESS', ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: 95, status: 'PENDING', ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: 165, status: 'PENDING', ownerDept: LAND_CELL },
      { name: 'Compensation disbursement', plannedIn: 225, status: 'PENDING', ownerDept: 'Finance and Compensation Department' },
    ],
    documents: [
      { documentType: 'SURVEY_PLAN', status: 'VERIFIED', count: 9 },
      { documentType: 'TITLE_DEED', status: 'VERIFIED', count: 11 },
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 2 },
      { documentType: 'IDENTITY_PROOF', status: 'SUBMITTED', count: 3 },
    ],
  },
  {
    projectCode: 'GJ-SRT-2026-031',
    name: 'Surat Riverfront Access Road',
    state: 'Gujarat',
    district: 'Surat',
    department: URBAN,
    projectType: 'URBAN_ROAD',
    priority: 'MEDIUM',
    status: 'ACTIVE',
    startedIn: -300,
    targetIn: 120,
    areaHectares: 27.9,
    stage: 'Section 23 award preparation',
    scenario:
      'An urban road where the municipality already held most of the land. Compensation is small, documents are verified, and the award is being drawn up on schedule.',
    expectedRisk: 'LOW',
    trajectory: 'IMPROVING',
    metrics: {
      parcelCount: 44,
      affectedLandownerCount: 52,
      unresolvedRecordCount: 2,
      objectionCount: 9,
      unresolvedObjectionCount: 4,
      requiredDocumentCount: 40,
      missingDocumentCount: 1,
      invalidDocumentCount: 0,
      documentVerificationPendingCount: 4,
      pendingApprovalCount: 2,
      blockedDependencyCount: 0,
      pendingCompensationAmount: 61_500_000,
      paymentProcessingDays: 21,
      openLegalCaseCount: 0,
      daysInCurrentStage: 29,
      averageStageDurationDays: 48,
      milestoneSlippageCount: 0,
      daysSinceLastUpdate: 4,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -280, status: 'COMPLETED', completedIn: -279, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -220, status: 'COMPLETED', completedIn: -218, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -140, status: 'COMPLETED', completedIn: -136, ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: -60, status: 'COMPLETED', completedIn: -58, ownerDept: LAND_CELL },
      { name: 'Section 23 award preparation', plannedIn: 35, status: 'IN_PROGRESS', ownerDept: 'Revenue Department' },
      { name: 'Compensation disbursement', plannedIn: 95, status: 'PENDING', ownerDept: 'Finance and Compensation Department' },
    ],
    documents: [
      { documentType: 'TITLE_DEED', status: 'VERIFIED', count: 16 },
      { documentType: 'AWARD_STATEMENT', status: 'SUBMITTED', count: 3 },
      { documentType: 'SURVEY_PLAN', status: 'VERIFIED', count: 7 },
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 1 },
    ],
  },
  {
    projectCode: 'TN-CBE-2026-009',
    name: 'Coimbatore Western Bypass Package 2',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    department: PWD,
    projectType: 'BYPASS',
    priority: 'MEDIUM',
    status: 'ACTIVE',
    startedIn: -520,
    targetIn: 60,
    areaHectares: 212.7,
    stage: 'Possession and handover',
    scenario:
      'A bypass in its final stage. Compensation has been paid, possession is being handed over, and the only outstanding items are closing documents.',
    expectedRisk: 'LOW',
    trajectory: 'IMPROVING',
    metrics: {
      parcelCount: 168,
      affectedLandownerCount: 203,
      unresolvedRecordCount: 3,
      objectionCount: 34,
      unresolvedObjectionCount: 5,
      requiredDocumentCount: 96,
      missingDocumentCount: 2,
      invalidDocumentCount: 0,
      documentVerificationPendingCount: 6,
      pendingApprovalCount: 1,
      blockedDependencyCount: 0,
      pendingCompensationAmount: 18_400_000,
      paymentProcessingDays: 15,
      openLegalCaseCount: 0,
      daysInCurrentStage: 22,
      averageStageDurationDays: 50,
      milestoneSlippageCount: 1,
      daysSinceLastUpdate: 2,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -500, status: 'COMPLETED', completedIn: -498, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -430, status: 'COMPLETED', completedIn: -424, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -340, status: 'COMPLETED', completedIn: -332, ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: -230, status: 'COMPLETED', completedIn: -228, ownerDept: LAND_CELL },
      { name: 'Section 23 award preparation', plannedIn: -140, status: 'COMPLETED', completedIn: -138, ownerDept: 'Revenue Department' },
      { name: 'Compensation disbursement', plannedIn: -50, status: 'COMPLETED', completedIn: -46, ownerDept: 'Finance and Compensation Department' },
      { name: 'Possession and handover', plannedIn: 40, status: 'IN_PROGRESS', ownerDept: PWD },
    ],
    documents: [
      { documentType: 'POSSESSION_CERTIFICATE', status: 'SUBMITTED', count: 8 },
      { documentType: 'PAYMENT_PROOF', status: 'VERIFIED', count: 22 },
      { documentType: 'TITLE_DEED', status: 'VERIFIED', count: 31 },
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 2 },
    ],
  },
];

// --- Medium risk ------------------------------------------------------------
// Cases where one or two things have drifted. These are the ones an early
// warning system earns its keep on: still recoverable, easy to miss.

const MEDIUM_RISK: DemoProject[] = [
  {
    projectCode: 'PB-LDH-2026-001',
    name: 'Ludhiana Ring Road Phase II',
    state: 'Punjab',
    district: 'Ludhiana',
    department: PWD,
    projectType: 'HIGHWAY',
    priority: 'HIGH',
    status: 'ACTIVE',
    startedIn: -340,
    targetIn: 95,
    areaHectares: 486.3,
    stage: 'Section 19 declaration',
    scenario:
      'A moderate corridor where documents have fallen behind and the declaration milestone has slipped twice. Nothing is broken yet, which is exactly when intervention is cheapest.',
    expectedRisk: 'MEDIUM',
    trajectory: 'WORSENING',
    metrics: {
      parcelCount: 184,
      affectedLandownerCount: 267,
      unresolvedRecordCount: 9,
      objectionCount: 41,
      unresolvedObjectionCount: 14,
      requiredDocumentCount: 88,
      missingDocumentCount: 11,
      invalidDocumentCount: 2,
      documentVerificationPendingCount: 13,
      pendingApprovalCount: 3,
      blockedDependencyCount: 1,
      pendingCompensationAmount: 184_000_000,
      paymentProcessingDays: 31,
      openLegalCaseCount: 0,
      daysInCurrentStage: 68,
      averageStageDurationDays: 55,
      milestoneSlippageCount: 2,
      daysSinceLastUpdate: 6,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -320, status: 'COMPLETED', completedIn: -316, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -250, status: 'COMPLETED', completedIn: -238, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -150, status: 'COMPLETED', completedIn: -132, ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: -18, status: 'OVERDUE', ownerDept: LAND_CELL },
      { name: 'Section 23 award preparation', plannedIn: 55, status: 'PENDING', ownerDept: 'Revenue Department' },
      { name: 'Compensation disbursement', plannedIn: 120, status: 'PENDING', ownerDept: 'Finance and Compensation Department' },
    ],
    documents: [
      { documentType: 'TITLE_DEED', status: 'VERIFIED', count: 24 },
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 7 },
      { documentType: 'ENCUMBRANCE_CERTIFICATE', status: 'REQUIRED', count: 4 },
      { documentType: 'SURVEY_PLAN', status: 'SUBMITTED', count: 13 },
      { documentType: 'IDENTITY_PROOF', status: 'REJECTED', count: 2 },
    ],
  },
  {
    projectCode: 'MH-NGP-2026-018',
    name: 'Nagpur Metro Reach 3 Extension',
    state: 'Maharashtra',
    district: 'Nagpur',
    department: URBAN,
    projectType: 'METRO_RAIL',
    priority: 'HIGH',
    status: 'ACTIVE',
    startedIn: -280,
    targetIn: 150,
    areaHectares: 64.1,
    stage: 'Section 15 objection review',
    scenario:
      'A metro extension where eighteen submitted documents are sitting unverified. The backlog is administrative, not adversarial, and it is holding up the objection review.',
    expectedRisk: 'MEDIUM',
    trajectory: 'WORSENING',
    metrics: {
      parcelCount: 97,
      affectedLandownerCount: 148,
      unresolvedRecordCount: 7,
      objectionCount: 26,
      unresolvedObjectionCount: 12,
      requiredDocumentCount: 72,
      missingDocumentCount: 6,
      invalidDocumentCount: 3,
      documentVerificationPendingCount: 18,
      pendingApprovalCount: 4,
      blockedDependencyCount: 1,
      pendingCompensationAmount: 129_500_000,
      paymentProcessingDays: 27,
      openLegalCaseCount: 0,
      daysInCurrentStage: 74,
      averageStageDurationDays: 58,
      milestoneSlippageCount: 1,
      daysSinceLastUpdate: 9,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -260, status: 'COMPLETED', completedIn: -257, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -190, status: 'COMPLETED', completedIn: -181, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -9, status: 'OVERDUE', ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: 70, status: 'PENDING', ownerDept: LAND_CELL },
      { name: 'Compensation disbursement', plannedIn: 140, status: 'PENDING', ownerDept: 'Finance and Compensation Department' },
    ],
    documents: [
      { documentType: 'TITLE_DEED', status: 'SUBMITTED', count: 12 },
      { documentType: 'MUTATION_RECORD', status: 'SUBMITTED', count: 6 },
      { documentType: 'OBJECTION_FILING', status: 'SUBMITTED', count: 9 },
      { documentType: 'ENCUMBRANCE_CERTIFICATE', status: 'REQUIRED', count: 4 },
      { documentType: 'IDENTITY_PROOF', status: 'REJECTED', count: 3 },
    ],
  },
  {
    projectCode: 'RJ-JAI-2026-026',
    name: 'Jaipur Outer Ring Road Package 6',
    state: 'Rajasthan',
    district: 'Jaipur',
    department: NHAI,
    projectType: 'HIGHWAY',
    priority: 'MEDIUM',
    status: 'ACTIVE',
    startedIn: -310,
    targetIn: 130,
    areaHectares: 398.2,
    stage: 'Section 15 objection review',
    scenario:
      'Fifty-eight objections outstanding, thirteen documents missing, and six approvals queued behind a single sanctioning officer. Three ordinary bottlenecks compounding.',
    expectedRisk: 'MEDIUM',
    trajectory: 'STABLE',
    metrics: {
      parcelCount: 241,
      affectedLandownerCount: 316,
      unresolvedRecordCount: 11,
      objectionCount: 63,
      unresolvedObjectionCount: 58,
      requiredDocumentCount: 104,
      missingDocumentCount: 13,
      invalidDocumentCount: 1,
      documentVerificationPendingCount: 9,
      pendingApprovalCount: 6,
      blockedDependencyCount: 3,
      pendingCompensationAmount: 246_800_000,
      paymentProcessingDays: 44,
      openLegalCaseCount: 0,
      daysInCurrentStage: 74,
      averageStageDurationDays: 60,
      milestoneSlippageCount: 1,
      daysSinceLastUpdate: 5,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -290, status: 'COMPLETED', completedIn: -287, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -220, status: 'COMPLETED', completedIn: -214, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: 25, status: 'IN_PROGRESS', ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: 85, status: 'PENDING', ownerDept: LAND_CELL },
      { name: 'Compensation disbursement', plannedIn: 155, status: 'PENDING', ownerDept: 'Finance and Compensation Department' },
    ],
    documents: [
      { documentType: 'OBJECTION_FILING', status: 'SUBMITTED', count: 14 },
      { documentType: 'TITLE_DEED', status: 'VERIFIED', count: 28 },
      { documentType: 'SURVEY_PLAN', status: 'VERIFIED', count: 11 },
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 5 },
    ],
  },
  {
    projectCode: 'MP-BPL-2026-012',
    name: 'Bhopal Water Grid Feeder Canal',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    department: WATER,
    projectType: 'IRRIGATION_CANAL',
    priority: 'MEDIUM',
    status: 'ACTIVE',
    startedIn: -240,
    targetIn: 165,
    areaHectares: 156.8,
    stage: 'Section 23 award preparation',
    scenario:
      'Compensation has been in processing for seventy-four days, well past the departmental window but not yet a crisis. Ten documents are outstanding behind it.',
    expectedRisk: 'MEDIUM',
    trajectory: 'WORSENING',
    metrics: {
      parcelCount: 128,
      affectedLandownerCount: 174,
      unresolvedRecordCount: 6,
      objectionCount: 22,
      unresolvedObjectionCount: 21,
      requiredDocumentCount: 66,
      missingDocumentCount: 10,
      invalidDocumentCount: 1,
      documentVerificationPendingCount: 7,
      pendingApprovalCount: 2,
      blockedDependencyCount: 0,
      pendingCompensationAmount: 143_700_000,
      compensationApprovalPendingFlag: true,
      paymentProcessingDays: 74,
      openLegalCaseCount: 0,
      daysInCurrentStage: 68,
      averageStageDurationDays: 52,
      milestoneSlippageCount: 1,
      daysSinceLastUpdate: 7,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -220, status: 'COMPLETED', completedIn: -217, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -160, status: 'COMPLETED', completedIn: -154, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -80, status: 'COMPLETED', completedIn: -72, ownerDept: LAND_CELL },
      { name: 'Section 23 award preparation', plannedIn: 40, status: 'IN_PROGRESS', ownerDept: 'Revenue Department' },
      { name: 'Compensation disbursement', plannedIn: 130, status: 'PENDING', ownerDept: 'Finance and Compensation Department' },
    ],
    documents: [
      { documentType: 'AWARD_STATEMENT', status: 'SUBMITTED', count: 6 },
      { documentType: 'TITLE_DEED', status: 'VERIFIED', count: 19 },
      { documentType: 'COMPENSATION_VOUCHER', status: 'SUBMITTED', count: 7 },
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 4 },
    ],
  },
  {
    projectCode: 'AP-VJA-2026-019',
    name: 'Vijayawada Industrial Access Corridor',
    state: 'Andhra Pradesh',
    district: 'NTR',
    department: INDUSTRY,
    projectType: 'INDUSTRIAL_CORRIDOR',
    priority: 'HIGH',
    status: 'ACTIVE',
    startedIn: -270,
    targetIn: 110,
    areaHectares: 289.5,
    stage: 'Section 19 declaration',
    scenario:
      'The declaration stage has been open eighty-one days against a fifty-five day baseline, with five approvals and three blocked dependencies behind it. Stagnation rather than conflict.',
    expectedRisk: 'MEDIUM',
    trajectory: 'WORSENING',
    metrics: {
      parcelCount: 163,
      affectedLandownerCount: 221,
      unresolvedRecordCount: 12,
      objectionCount: 31,
      unresolvedObjectionCount: 13,
      requiredDocumentCount: 78,
      missingDocumentCount: 7,
      invalidDocumentCount: 2,
      documentVerificationPendingCount: 11,
      pendingApprovalCount: 5,
      blockedDependencyCount: 3,
      pendingCompensationAmount: 198_300_000,
      paymentProcessingDays: 29,
      openLegalCaseCount: 0,
      daysInCurrentStage: 81,
      averageStageDurationDays: 55,
      milestoneSlippageCount: 2,
      daysSinceLastUpdate: 11,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -250, status: 'COMPLETED', completedIn: -246, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -180, status: 'COMPLETED', completedIn: -169, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -100, status: 'COMPLETED', completedIn: -84, ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: -12, status: 'OVERDUE', ownerDept: LAND_CELL },
      { name: 'Compensation disbursement', plannedIn: 95, status: 'PENDING', ownerDept: 'Finance and Compensation Department' },
    ],
    documents: [
      { documentType: 'TITLE_DEED', status: 'VERIFIED', count: 21 },
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 5 },
      { documentType: 'SURVEY_PLAN', status: 'SUBMITTED', count: 8 },
      { documentType: 'IDENTITY_PROOF', status: 'REJECTED', count: 2 },
    ],
  },
  {
    projectCode: 'GJ-RJT-2026-028',
    name: 'Rajkot Eastern Bypass',
    state: 'Gujarat',
    district: 'Rajkot',
    department: PWD,
    projectType: 'BYPASS',
    priority: 'MEDIUM',
    status: 'ACTIVE',
    startedIn: -220,
    targetIn: 145,
    areaHectares: 174.3,
    stage: 'Survey and demarcation',
    scenario:
      'Fourteen required documents are outstanding on a case file of sixty-two, and the survey milestone is three weeks late. The paperwork is the schedule.',
    expectedRisk: 'MEDIUM',
    trajectory: 'STABLE',
    metrics: {
      parcelCount: 112,
      affectedLandownerCount: 143,
      unresolvedRecordCount: 8,
      objectionCount: 17,
      unresolvedObjectionCount: 8,
      requiredDocumentCount: 62,
      missingDocumentCount: 14,
      invalidDocumentCount: 2,
      documentVerificationPendingCount: 8,
      pendingApprovalCount: 2,
      blockedDependencyCount: 1,
      pendingCompensationAmount: 87_900_000,
      paymentProcessingDays: 19,
      openLegalCaseCount: 0,
      daysInCurrentStage: 58,
      averageStageDurationDays: 50,
      milestoneSlippageCount: 1,
      daysSinceLastUpdate: 8,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -200, status: 'COMPLETED', completedIn: -196, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -21, status: 'OVERDUE', ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: 60, status: 'PENDING', ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: 120, status: 'PENDING', ownerDept: LAND_CELL },
    ],
    documents: [
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 8 },
      { documentType: 'ENCUMBRANCE_CERTIFICATE', status: 'REQUIRED', count: 6 },
      { documentType: 'TITLE_DEED', status: 'VERIFIED', count: 15 },
      { documentType: 'SURVEY_PLAN', status: 'SUBMITTED', count: 8 },
    ],
  },
  {
    projectCode: 'AS-KAM-2026-005',
    name: 'Guwahati Railway Over Bridge Approach',
    state: 'Assam',
    district: 'Kamrup Metropolitan',
    department: RAIL,
    projectType: 'RAILWAY_LINE',
    priority: 'MEDIUM',
    status: 'ACTIVE',
    startedIn: -200,
    targetIn: 175,
    areaHectares: 38.6,
    stage: 'Section 15 objection review',
    scenario:
      'Four dependencies are blocked between the railway and the municipal corporation. Small in land terms, held up entirely by coordination.',
    expectedRisk: 'MEDIUM',
    trajectory: 'STABLE',
    metrics: {
      parcelCount: 47,
      affectedLandownerCount: 71,
      unresolvedRecordCount: 5,
      objectionCount: 14,
      unresolvedObjectionCount: 7,
      requiredDocumentCount: 44,
      missingDocumentCount: 5,
      invalidDocumentCount: 1,
      documentVerificationPendingCount: 9,
      pendingApprovalCount: 4,
      blockedDependencyCount: 4,
      pendingCompensationAmount: 52_400_000,
      paymentProcessingDays: 26,
      openLegalCaseCount: 0,
      daysInCurrentStage: 63,
      averageStageDurationDays: 54,
      milestoneSlippageCount: 1,
      daysSinceLastUpdate: 13,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -180, status: 'COMPLETED', completedIn: -177, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -110, status: 'COMPLETED', completedIn: -101, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: 15, status: 'IN_PROGRESS', ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: 100, status: 'PENDING', ownerDept: LAND_CELL },
    ],
    documents: [
      { documentType: 'OBJECTION_FILING', status: 'SUBMITTED', count: 7 },
      { documentType: 'TITLE_DEED', status: 'SUBMITTED', count: 9 },
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 5 },
      { documentType: 'SURVEY_PLAN', status: 'VERIFIED', count: 6 },
    ],
  },
];

// --- High risk --------------------------------------------------------------
// Several bottlenecks at once, or one serious one. These need an owner and a
// date, and they are where the recommendation ranking has to be right.

const HIGH_RISK: DemoProject[] = [
  {
    projectCode: 'PB-ASR-2026-003',
    name: 'Amritsar-Jalandhar Expressway Package 3',
    state: 'Punjab',
    district: 'Amritsar',
    department: NHAI,
    projectType: 'EXPRESSWAY',
    priority: 'CRITICAL',
    status: 'ACTIVE',
    startedIn: -480,
    targetIn: 40,
    areaHectares: 612.4,
    stage: 'Compensation disbursement',
    scenario:
      'Sixty-eight parcels with disputed title, compensation ninety-four days in processing, and two civil suits filed. Three separate bottlenecks, each with a different owner.',
    expectedRisk: 'HIGH',
    trajectory: 'WORSENING',
    metrics: {
      parcelCount: 287,
      affectedLandownerCount: 394,
      unresolvedRecordCount: 68,
      disputedOwnershipFlag: true,
      objectionCount: 118,
      unresolvedObjectionCount: 47,
      requiredDocumentCount: 142,
      missingDocumentCount: 21,
      invalidDocumentCount: 6,
      documentVerificationPendingCount: 19,
      pendingApprovalCount: 7,
      blockedDependencyCount: 3,
      pendingCompensationAmount: 634_000_000,
      compensationApprovalPendingFlag: true,
      paymentProcessingDays: 94,
      openLegalCaseCount: 2,
      legalDisputeFlag: true,
      daysInCurrentStage: 118,
      averageStageDurationDays: 62,
      milestoneSlippageCount: 4,
      daysSinceLastUpdate: 9,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -460, status: 'COMPLETED', completedIn: -452, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -380, status: 'COMPLETED', completedIn: -358, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -270, status: 'COMPLETED', completedIn: -231, ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: -160, status: 'COMPLETED', completedIn: -134, ownerDept: LAND_CELL },
      { name: 'Section 23 award preparation', plannedIn: -70, status: 'COMPLETED', completedIn: -48, ownerDept: 'Revenue Department' },
      { name: 'Compensation disbursement', plannedIn: -38, status: 'OVERDUE', ownerDept: 'Finance and Compensation Department' },
      { name: 'Possession and handover', plannedIn: 35, status: 'PENDING', ownerDept: NHAI },
    ],
    documents: [
      { documentType: 'TITLE_DEED', status: 'REJECTED', count: 6 },
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 12 },
      { documentType: 'ENCUMBRANCE_CERTIFICATE', status: 'REQUIRED', count: 9 },
      { documentType: 'LEGAL_NOTICE', status: 'SUBMITTED', count: 4 },
      { documentType: 'COMPENSATION_VOUCHER', status: 'SUBMITTED', count: 15 },
    ],
  },
  {
    projectCode: 'MH-PUN-2026-011',
    name: 'Pune Outer Ring Road Package 7',
    state: 'Maharashtra',
    district: 'Pune',
    department: PWD,
    projectType: 'HIGHWAY',
    priority: 'HIGH',
    status: 'ACTIVE',
    startedIn: -400,
    targetIn: 70,
    areaHectares: 524.9,
    stage: 'Section 15 objection review',
    scenario:
      'Sixty-eight unresolved objections against 312 landowners, with forty-one parcels of unresolved title behind them. The objections and the title defects are the same dispute seen twice.',
    expectedRisk: 'HIGH',
    trajectory: 'WORSENING',
    metrics: {
      parcelCount: 231,
      affectedLandownerCount: 312,
      unresolvedRecordCount: 41,
      disputedOwnershipFlag: true,
      objectionCount: 164,
      unresolvedObjectionCount: 68,
      requiredDocumentCount: 118,
      missingDocumentCount: 16,
      invalidDocumentCount: 4,
      documentVerificationPendingCount: 22,
      pendingApprovalCount: 5,
      blockedDependencyCount: 2,
      pendingCompensationAmount: 498_200_000,
      paymentProcessingDays: 41,
      openLegalCaseCount: 1,
      legalDisputeFlag: true,
      daysInCurrentStage: 108,
      averageStageDurationDays: 60,
      milestoneSlippageCount: 2,
      daysSinceLastUpdate: 14,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -380, status: 'COMPLETED', completedIn: -374, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -300, status: 'COMPLETED', completedIn: -281, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -52, status: 'OVERDUE', ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: 45, status: 'PENDING', ownerDept: LAND_CELL },
      { name: 'Compensation disbursement', plannedIn: 130, status: 'PENDING', ownerDept: 'Finance and Compensation Department' },
    ],
    documents: [
      { documentType: 'OBJECTION_FILING', status: 'SUBMITTED', count: 26 },
      { documentType: 'TITLE_DEED', status: 'REJECTED', count: 4 },
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 10 },
      { documentType: 'HEARING_ORDER', status: 'REQUIRED', count: 6 },
    ],
  },
  {
    projectCode: 'TN-CHN-2026-016',
    name: 'Chennai Peripheral Logistics Hub',
    state: 'Tamil Nadu',
    district: 'Chengalpattu',
    department: INDUSTRY,
    projectType: 'LOGISTICS_HUB',
    priority: 'HIGH',
    status: 'ACTIVE',
    startedIn: -360,
    targetIn: 55,
    areaHectares: 341.7,
    stage: 'Compensation disbursement',
    scenario:
      'Compensation has been in processing for 118 days against a forty-five day window, with the disbursement milestone sixty-three days overdue. A financial bottleneck that has become a schedule one.',
    expectedRisk: 'HIGH',
    trajectory: 'WORSENING',
    metrics: {
      parcelCount: 198,
      affectedLandownerCount: 246,
      unresolvedRecordCount: 22,
      objectionCount: 58,
      unresolvedObjectionCount: 26,
      requiredDocumentCount: 96,
      missingDocumentCount: 13,
      invalidDocumentCount: 3,
      documentVerificationPendingCount: 16,
      pendingApprovalCount: 6,
      blockedDependencyCount: 2,
      pendingCompensationAmount: 721_500_000,
      compensationApprovalPendingFlag: true,
      paymentProcessingDays: 118,
      openLegalCaseCount: 1,
      daysInCurrentStage: 96,
      averageStageDurationDays: 58,
      milestoneSlippageCount: 3,
      daysSinceLastUpdate: 12,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -340, status: 'COMPLETED', completedIn: -336, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -270, status: 'COMPLETED', completedIn: -258, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -190, status: 'COMPLETED', completedIn: -168, ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: -110, status: 'COMPLETED', completedIn: -96, ownerDept: LAND_CELL },
      { name: 'Compensation disbursement', plannedIn: -63, status: 'OVERDUE', ownerDept: 'Finance and Compensation Department' },
      { name: 'Possession and handover', plannedIn: 50, status: 'PENDING', ownerDept: INDUSTRY },
    ],
    documents: [
      { documentType: 'COMPENSATION_VOUCHER', status: 'SUBMITTED', count: 18 },
      { documentType: 'PAYMENT_PROOF', status: 'REQUIRED', count: 11 },
      { documentType: 'TITLE_DEED', status: 'VERIFIED', count: 26 },
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 6 },
    ],
  },
  {
    projectCode: 'UP-KNP-2026-021',
    name: 'Kanpur Defence Corridor Link Road',
    state: 'Uttar Pradesh',
    district: 'Kanpur Nagar',
    department: INDUSTRY,
    projectType: 'INDUSTRIAL_CORRIDOR',
    priority: 'HIGH',
    status: 'ACTIVE',
    startedIn: -430,
    targetIn: 65,
    areaHectares: 447.2,
    stage: 'Section 23 award preparation',
    scenario:
      'Thirty-eight parcels of unresolved title, seven approvals stacked in one queue, and four milestones already rescheduled. The record has not been touched in nearly four weeks.',
    expectedRisk: 'HIGH',
    trajectory: 'WORSENING',
    metrics: {
      parcelCount: 216,
      affectedLandownerCount: 289,
      unresolvedRecordCount: 38,
      disputedOwnershipFlag: true,
      objectionCount: 71,
      unresolvedObjectionCount: 33,
      requiredDocumentCount: 108,
      missingDocumentCount: 19,
      invalidDocumentCount: 5,
      documentVerificationPendingCount: 14,
      pendingApprovalCount: 7,
      blockedDependencyCount: 4,
      pendingCompensationAmount: 512_800_000,
      paymentProcessingDays: 47,
      openLegalCaseCount: 1,
      daysInCurrentStage: 142,
      averageStageDurationDays: 64,
      milestoneSlippageCount: 4,
      daysSinceLastUpdate: 26,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -410, status: 'COMPLETED', completedIn: -402, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -330, status: 'COMPLETED', completedIn: -308, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -240, status: 'COMPLETED', completedIn: -205, ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: -150, status: 'COMPLETED', completedIn: -121, ownerDept: LAND_CELL },
      { name: 'Section 23 award preparation', plannedIn: -44, status: 'OVERDUE', ownerDept: 'Revenue Department' },
      { name: 'Compensation disbursement', plannedIn: 55, status: 'PENDING', ownerDept: 'Finance and Compensation Department' },
    ],
    documents: [
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 11 },
      { documentType: 'TITLE_DEED', status: 'REJECTED', count: 5 },
      { documentType: 'ENCUMBRANCE_CERTIFICATE', status: 'REQUIRED', count: 8 },
      { documentType: 'AWARD_STATEMENT', status: 'SUBMITTED', count: 7 },
    ],
  },
  {
    projectCode: 'MH-NSK-2026-024',
    name: 'Nashik-Sinnar Industrial Corridor',
    state: 'Maharashtra',
    district: 'Nashik',
    department: INDUSTRY,
    projectType: 'INDUSTRIAL_CORRIDOR',
    priority: 'HIGH',
    status: 'ACTIVE',
    startedIn: -350,
    targetIn: 80,
    areaHectares: 378.4,
    stage: 'Section 19 declaration',
    scenario:
      'Sixty-two objections outstanding, twenty-four documents missing, and the declaration thirty-nine days late. Three groups of problems, none of them yet legal.',
    expectedRisk: 'HIGH',
    trajectory: 'WORSENING',
    metrics: {
      parcelCount: 187,
      affectedLandownerCount: 234,
      unresolvedRecordCount: 29,
      objectionCount: 94,
      unresolvedObjectionCount: 62,
      requiredDocumentCount: 92,
      missingDocumentCount: 24,
      invalidDocumentCount: 4,
      documentVerificationPendingCount: 17,
      pendingApprovalCount: 6,
      blockedDependencyCount: 3,
      pendingCompensationAmount: 367_900_000,
      paymentProcessingDays: 38,
      openLegalCaseCount: 0,
      daysInCurrentStage: 108,
      averageStageDurationDays: 56,
      milestoneSlippageCount: 3,
      daysSinceLastUpdate: 16,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -330, status: 'COMPLETED', completedIn: -324, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -260, status: 'COMPLETED', completedIn: -244, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -170, status: 'COMPLETED', completedIn: -142, ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: -39, status: 'OVERDUE', ownerDept: LAND_CELL },
      { name: 'Compensation disbursement', plannedIn: 70, status: 'PENDING', ownerDept: 'Finance and Compensation Department' },
    ],
    documents: [
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 13 },
      { documentType: 'OBJECTION_FILING', status: 'SUBMITTED', count: 17 },
      { documentType: 'ENCUMBRANCE_CERTIFICATE', status: 'REQUIRED', count: 11 },
      { documentType: 'TITLE_DEED', status: 'VERIFIED', count: 18 },
    ],
  },
  {
    projectCode: 'BR-PAT-2026-013',
    name: 'Patna Ganga Path Eastern Extension',
    state: 'Bihar',
    district: 'Patna',
    department: URBAN,
    projectType: 'URBAN_ROAD',
    priority: 'HIGH',
    status: 'ACTIVE',
    startedIn: -390,
    targetIn: 50,
    areaHectares: 163.5,
    stage: 'Section 23 award preparation',
    scenario:
      'Three civil suits over compensation rates, with payment eighty-one days in processing behind them. The legal challenge and the payment delay are feeding each other.',
    expectedRisk: 'HIGH',
    trajectory: 'SPIKING',
    metrics: {
      parcelCount: 142,
      affectedLandownerCount: 198,
      unresolvedRecordCount: 26,
      objectionCount: 67,
      unresolvedObjectionCount: 31,
      requiredDocumentCount: 84,
      missingDocumentCount: 12,
      invalidDocumentCount: 3,
      documentVerificationPendingCount: 13,
      pendingApprovalCount: 4,
      blockedDependencyCount: 2,
      pendingCompensationAmount: 289_400_000,
      compensationApprovalPendingFlag: true,
      paymentProcessingDays: 81,
      openLegalCaseCount: 3,
      legalDisputeFlag: true,
      daysInCurrentStage: 87,
      averageStageDurationDays: 54,
      milestoneSlippageCount: 2,
      daysSinceLastUpdate: 8,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -370, status: 'COMPLETED', completedIn: -366, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -300, status: 'COMPLETED', completedIn: -289, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -210, status: 'COMPLETED', completedIn: -186, ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: -120, status: 'COMPLETED', completedIn: -108, ownerDept: LAND_CELL },
      { name: 'Section 23 award preparation', plannedIn: -26, status: 'OVERDUE', ownerDept: 'Revenue Department' },
      { name: 'Compensation disbursement', plannedIn: 40, status: 'PENDING', ownerDept: 'Finance and Compensation Department' },
    ],
    documents: [
      { documentType: 'LEGAL_NOTICE', status: 'SUBMITTED', count: 8 },
      { documentType: 'COURT_ORDER', status: 'SUBMITTED', count: 3 },
      { documentType: 'COMPENSATION_VOUCHER', status: 'SUBMITTED', count: 9 },
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 7 },
    ],
  },
  {
    projectCode: 'MP-IDR-2026-027',
    name: 'Indore Metro Depot Land Assembly',
    state: 'Madhya Pradesh',
    district: 'Indore',
    department: URBAN,
    projectType: 'METRO_RAIL',
    priority: 'HIGH',
    status: 'ACTIVE',
    startedIn: -320,
    targetIn: 85,
    areaHectares: 72.8,
    stage: 'Section 15 objection review',
    scenario:
      'A compact depot site where twenty-four of ninety-four parcels have contested title. A small acquisition can be a hard one when the ownership is tangled.',
    expectedRisk: 'HIGH',
    trajectory: 'STABLE',
    metrics: {
      parcelCount: 94,
      affectedLandownerCount: 161,
      unresolvedRecordCount: 24,
      disputedOwnershipFlag: true,
      objectionCount: 73,
      unresolvedObjectionCount: 33,
      requiredDocumentCount: 68,
      missingDocumentCount: 15,
      invalidDocumentCount: 4,
      documentVerificationPendingCount: 12,
      pendingApprovalCount: 4,
      blockedDependencyCount: 2,
      pendingCompensationAmount: 214_600_000,
      paymentProcessingDays: 44,
      openLegalCaseCount: 1,
      legalDisputeFlag: true,
      daysInCurrentStage: 102,
      averageStageDurationDays: 58,
      milestoneSlippageCount: 2,
      daysSinceLastUpdate: 10,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -300, status: 'COMPLETED', completedIn: -295, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -230, status: 'COMPLETED', completedIn: -213, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -31, status: 'OVERDUE', ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: 60, status: 'PENDING', ownerDept: LAND_CELL },
    ],
    documents: [
      { documentType: 'TITLE_DEED', status: 'REJECTED', count: 7 },
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 9 },
      { documentType: 'OBJECTION_FILING', status: 'SUBMITTED', count: 12 },
      { documentType: 'ENCUMBRANCE_CERTIFICATE', status: 'REQUIRED', count: 6 },
    ],
  },
  {
    projectCode: 'KA-DWD-2026-030',
    name: 'Hubballi-Ankola Railway Link Section 2',
    state: 'Karnataka',
    district: 'Dharwad',
    department: RAIL,
    projectType: 'RAILWAY_LINE',
    priority: 'HIGH',
    status: 'ACTIVE',
    startedIn: -370,
    targetIn: 90,
    areaHectares: 296.1,
    stage: 'Section 19 declaration',
    scenario:
      'Forty-one objections, twenty-two missing documents, and four dependencies blocked across three departments. No single owner can clear this alone.',
    expectedRisk: 'HIGH',
    trajectory: 'WORSENING',
    metrics: {
      parcelCount: 176,
      affectedLandownerCount: 218,
      unresolvedRecordCount: 31,
      objectionCount: 88,
      unresolvedObjectionCount: 41,
      requiredDocumentCount: 86,
      missingDocumentCount: 22,
      invalidDocumentCount: 5,
      documentVerificationPendingCount: 15,
      pendingApprovalCount: 7,
      blockedDependencyCount: 4,
      pendingCompensationAmount: 331_200_000,
      paymentProcessingDays: 36,
      openLegalCaseCount: 0,
      daysInCurrentStage: 114,
      averageStageDurationDays: 57,
      milestoneSlippageCount: 3,
      daysSinceLastUpdate: 19,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -350, status: 'COMPLETED', completedIn: -344, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -280, status: 'COMPLETED', completedIn: -261, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -190, status: 'COMPLETED', completedIn: -158, ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: -34, status: 'OVERDUE', ownerDept: LAND_CELL },
      { name: 'Compensation disbursement', plannedIn: 80, status: 'PENDING', ownerDept: 'Finance and Compensation Department' },
    ],
    documents: [
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 12 },
      { documentType: 'OBJECTION_FILING', status: 'SUBMITTED', count: 15 },
      { documentType: 'SURVEY_PLAN', status: 'REJECTED', count: 5 },
      { documentType: 'ENCUMBRANCE_CERTIFICATE', status: 'REQUIRED', count: 10 },
    ],
  },
];

// --- Critical risk ----------------------------------------------------------
// A governed hard stop, or so many severe bottlenecks at once that the case has
// effectively halted. These drive the critical band on every chart.

const CRITICAL_RISK: DemoProject[] = [
  {
    projectCode: 'MH-MUM-2026-002',
    name: 'Mumbai Coastal Freight Corridor Package 2',
    state: 'Maharashtra',
    district: 'Mumbai Suburban',
    department: URBAN,
    projectType: 'EXPRESSWAY',
    priority: 'CRITICAL',
    status: 'ACTIVE',
    startedIn: -640,
    targetIn: -45,
    areaHectares: 289.3,
    stage: 'Section 15 objection review',
    scenario:
      'Severe ownership disputes across 142 parcels, 218 unresolved objections, six civil suits, and a declaration milestone 187 days overdue. The target date has already passed.',
    expectedRisk: 'CRITICAL',
    trajectory: 'WORSENING',
    metrics: {
      parcelCount: 264,
      affectedLandownerCount: 487,
      unresolvedRecordCount: 142,
      disputedOwnershipFlag: true,
      objectionCount: 356,
      unresolvedObjectionCount: 218,
      requiredDocumentCount: 156,
      missingDocumentCount: 47,
      invalidDocumentCount: 12,
      documentVerificationPendingCount: 34,
      pendingApprovalCount: 14,
      blockedDependencyCount: 8,
      pendingCompensationAmount: 1_284_000_000,
      compensationApprovalPendingFlag: true,
      paymentProcessingDays: 162,
      openLegalCaseCount: 6,
      legalDisputeFlag: true,
      daysInCurrentStage: 241,
      averageStageDurationDays: 60,
      milestoneSlippageCount: 7,
      daysSinceLastUpdate: 21,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -620, status: 'COMPLETED', completedIn: -604, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -520, status: 'COMPLETED', completedIn: -468, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -187, status: 'OVERDUE', ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: -90, status: 'OVERDUE', ownerDept: LAND_CELL },
      { name: 'Section 23 award preparation', plannedIn: -20, status: 'PENDING', ownerDept: 'Revenue Department' },
      { name: 'Compensation disbursement', plannedIn: 60, status: 'PENDING', ownerDept: 'Finance and Compensation Department' },
    ],
    documents: [
      { documentType: 'TITLE_DEED', status: 'REJECTED', count: 14 },
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 22 },
      { documentType: 'COURT_ORDER', status: 'SUBMITTED', count: 6 },
      { documentType: 'LEGAL_NOTICE', status: 'SUBMITTED', count: 11 },
      { documentType: 'OBJECTION_FILING', status: 'SUBMITTED', count: 31 },
      { documentType: 'ENCUMBRANCE_CERTIFICATE', status: 'REQUIRED', count: 13 },
    ],
  },
  {
    projectCode: 'HR-GGN-2026-004',
    name: 'Gurugram-Sohna Elevated Corridor',
    state: 'Haryana',
    district: 'Gurugram',
    department: NHAI,
    projectType: 'EXPRESSWAY',
    priority: 'CRITICAL',
    status: 'ON_HOLD',
    startedIn: -520,
    targetIn: -10,
    areaHectares: 198.6,
    stage: 'Section 19 declaration',
    scenario:
      'A High Court stay order is in force. This is a governed hard stop: the system classifies it CRITICAL regardless of every other measurement, and recommends holding any step the order restrains.',
    expectedRisk: 'CRITICAL',
    trajectory: 'SPIKING',
    metrics: {
      parcelCount: 152,
      affectedLandownerCount: 241,
      unresolvedRecordCount: 47,
      disputedOwnershipFlag: true,
      objectionCount: 128,
      unresolvedObjectionCount: 76,
      requiredDocumentCount: 94,
      missingDocumentCount: 18,
      invalidDocumentCount: 6,
      documentVerificationPendingCount: 21,
      pendingApprovalCount: 8,
      blockedDependencyCount: 4,
      pendingCompensationAmount: 642_700_000,
      compensationApprovalPendingFlag: true,
      paymentProcessingDays: 97,
      openLegalCaseCount: 4,
      legalDisputeFlag: true,
      stayOrderFlag: true,
      daysInCurrentStage: 168,
      averageStageDurationDays: 58,
      milestoneSlippageCount: 5,
      daysSinceLastUpdate: 15,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -500, status: 'COMPLETED', completedIn: -492, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -420, status: 'COMPLETED', completedIn: -391, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -300, status: 'COMPLETED', completedIn: -248, ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: -124, status: 'OVERDUE', ownerDept: LAND_CELL },
      { name: 'Compensation disbursement', plannedIn: 30, status: 'PENDING', ownerDept: 'Finance and Compensation Department' },
    ],
    documents: [
      { documentType: 'COURT_ORDER', status: 'SUBMITTED', count: 4 },
      { documentType: 'LEGAL_NOTICE', status: 'SUBMITTED', count: 9 },
      { documentType: 'TITLE_DEED', status: 'REJECTED', count: 8 },
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 14 },
    ],
  },
  {
    projectCode: 'UP-VNS-2026-006',
    name: 'Varanasi Ring Road Phase III',
    state: 'Uttar Pradesh',
    district: 'Varanasi',
    department: NHAI,
    projectType: 'HIGHWAY',
    priority: 'CRITICAL',
    status: 'ACTIVE',
    startedIn: -580,
    targetIn: -70,
    areaHectares: 534.8,
    stage: 'Section 23 award preparation',
    scenario:
      'Compensation of 1.6 billion rupees has been in processing for 203 days, with 98 parcels of unresolved title and five suits. The case has stopped moving without anyone declaring it stopped.',
    expectedRisk: 'CRITICAL',
    trajectory: 'WORSENING',
    metrics: {
      parcelCount: 312,
      affectedLandownerCount: 428,
      unresolvedRecordCount: 98,
      disputedOwnershipFlag: true,
      objectionCount: 241,
      unresolvedObjectionCount: 147,
      requiredDocumentCount: 168,
      missingDocumentCount: 39,
      invalidDocumentCount: 9,
      documentVerificationPendingCount: 28,
      pendingApprovalCount: 11,
      blockedDependencyCount: 6,
      pendingCompensationAmount: 1_612_000_000,
      compensationApprovalPendingFlag: true,
      paymentProcessingDays: 203,
      openLegalCaseCount: 5,
      legalDisputeFlag: true,
      daysInCurrentStage: 214,
      averageStageDurationDays: 62,
      milestoneSlippageCount: 6,
      daysSinceLastUpdate: 28,
    },
    milestones: [
      { name: 'Section 11 preliminary notification', plannedIn: -560, status: 'COMPLETED', completedIn: -548, ownerDept: LAND_CELL },
      { name: 'Survey and demarcation', plannedIn: -470, status: 'COMPLETED', completedIn: -431, ownerDept: 'Revenue Department' },
      { name: 'Section 15 objection review', plannedIn: -360, status: 'COMPLETED', completedIn: -294, ownerDept: LAND_CELL },
      { name: 'Section 19 declaration', plannedIn: -250, status: 'COMPLETED', completedIn: -198, ownerDept: LAND_CELL },
      { name: 'Section 23 award preparation', plannedIn: -152, status: 'OVERDUE', ownerDept: 'Revenue Department' },
      { name: 'Compensation disbursement', plannedIn: -40, status: 'OVERDUE', ownerDept: 'Finance and Compensation Department' },
    ],
    documents: [
      { documentType: 'COMPENSATION_VOUCHER', status: 'SUBMITTED', count: 24 },
      { documentType: 'PAYMENT_PROOF', status: 'REQUIRED', count: 19 },
      { documentType: 'TITLE_DEED', status: 'REJECTED', count: 11 },
      { documentType: 'MUTATION_RECORD', status: 'REQUIRED', count: 20 },
      { documentType: 'LEGAL_NOTICE', status: 'SUBMITTED', count: 7 },
    ],
  },
];

export const DEMO_PROJECTS: readonly DemoProject[] = [...LOW_RISK, ...MEDIUM_RISK, ...HIGH_RISK, ...CRITICAL_RISK];

/** The distribution the dataset is built to demonstrate. A test verifies it. */
export const EXPECTED_DISTRIBUTION: Record<RiskBand, number> = { LOW: 5, MEDIUM: 7, HIGH: 8, CRITICAL: 3 };

/**
 * Multipliers applied to the current score to build six months of history.
 * The last entry is always 1, so the series ends at the score the engine
 * derives today rather than at an independently invented number.
 */
export const TRAJECTORY_CURVES: Record<Trajectory, number[]> = {
  IMPROVING: [1.42, 1.34, 1.25, 1.16, 1.08, 1],
  STABLE: [0.94, 0.97, 0.95, 0.99, 0.98, 1],
  WORSENING: [0.58, 0.66, 0.74, 0.83, 0.92, 1],
  SPIKING: [0.52, 0.55, 0.57, 0.61, 0.79, 1],
};
