/**
 * GENERATED FILE. DO NOT EDIT BY HAND.
 *
 * Produced by `backend/scripts/generateDemoFallback.ts` from the demonstration
 * dataset in `backend/prisma/demoDataset.ts`, scored by the same rule engine the
 * API uses. Regenerate with:
 *
 *     npm --prefix backend run generate:demo-fallback
 *
 * This is the offline fallback only. When the API is reachable the dashboard
 * reads `/analytics/dashboard`, which is computed from the database. Nothing
 * here is an independent source of truth, which is why it is generated rather
 * than written: a hand-authored copy drifts from the database the first time a
 * case fact changes.
 *
 * Reference date: 2026-09-16T09:00:00.000Z
 * Derived risk distribution: CRITICAL 3, HIGH 8, LOW 5, MEDIUM 7
 */

import type { DashboardData, Project, Risk } from './types/project';

export type { Project, Risk };

export const projects: Project[] = [
  {
    "id": "KA-BLR-2026-014",
    "name": "Bengaluru Peripheral Ring Road Package 4",
    "district": "Bengaluru Rural",
    "department": "National Highways Authority",
    "state": "Karnataka",
    "stage": "Compensation disbursement",
    "progress": 71,
    "probability": 0.02915,
    "expectedDelay": 2,
    "risk": "LOW",
    "factor": "Compensation ageing in processing",
    "updated": "2 days ago",
    "parcels": 892,
    "owners": 1240,
    "objections": 11,
    "compensation": "₹41.2 Cr pending",
    "legal": "No active cases",
    "targetDate": "15 Mar 2027",
    "area": "7 stages"
  },
  {
    "id": "KL-EKM-2026-007",
    "name": "Kochi Water Supply Augmentation Main",
    "district": "Ernakulam",
    "department": "Water Resources",
    "state": "Kerala",
    "stage": "Section 19 declaration",
    "progress": 50,
    "probability": 0.08651,
    "expectedDelay": 5,
    "risk": "LOW",
    "factor": "Unresolved landowner objections",
    "updated": "Yesterday",
    "parcels": 31,
    "owners": 29,
    "objections": 3,
    "compensation": "₹2.5 Cr pending",
    "legal": "No active cases",
    "targetDate": "14 Apr 2027",
    "area": "6 stages"
  },
  {
    "id": "MH-NSK-2026-022",
    "name": "Nashik Solar Park Transmission Corridor",
    "district": "Nashik",
    "department": "Energy and Power",
    "state": "Maharashtra",
    "stage": "Survey and demarcation",
    "progress": 20,
    "probability": 0.066,
    "expectedDelay": 4,
    "risk": "LOW",
    "factor": "Required documents missing",
    "updated": "3 days ago",
    "parcels": 58,
    "owners": 64,
    "objections": 4,
    "compensation": "₹3.8 Cr pending",
    "legal": "No active cases",
    "targetDate": "14 May 2027",
    "area": "5 stages"
  },
  {
    "id": "GJ-SRT-2026-031",
    "name": "Surat Riverfront Access Road",
    "district": "Surat",
    "department": "Urban Development",
    "state": "Gujarat",
    "stage": "Section 23 award preparation",
    "progress": 67,
    "probability": 0.09347,
    "expectedDelay": 6,
    "risk": "LOW",
    "factor": "Unresolved ownership records",
    "updated": "4 days ago",
    "parcels": 44,
    "owners": 52,
    "objections": 4,
    "compensation": "₹6.2 Cr pending",
    "legal": "No active cases",
    "targetDate": "14 Jan 2027",
    "area": "6 stages"
  },
  {
    "id": "TN-CBE-2026-009",
    "name": "Coimbatore Western Bypass Package 2",
    "district": "Coimbatore",
    "department": "Public Works Department",
    "state": "Tamil Nadu",
    "stage": "Possession and handover",
    "progress": 86,
    "probability": 0.00106,
    "expectedDelay": 3,
    "risk": "LOW",
    "factor": "Required documents missing",
    "updated": "2 days ago",
    "parcels": 168,
    "owners": 203,
    "objections": 5,
    "compensation": "₹1.8 Cr pending",
    "legal": "No active cases",
    "targetDate": "15 Nov 2026",
    "area": "7 stages"
  },
  {
    "id": "PB-LDH-2026-001",
    "name": "Ludhiana Ring Road Phase II",
    "district": "Ludhiana",
    "department": "Public Works Department",
    "state": "Punjab",
    "stage": "Section 19 declaration",
    "progress": 50,
    "probability": 0.29305,
    "expectedDelay": 29,
    "risk": "MEDIUM",
    "factor": "Required documents missing",
    "updated": "6 days ago",
    "parcels": 184,
    "owners": 267,
    "objections": 14,
    "compensation": "₹18.4 Cr pending",
    "legal": "No active cases",
    "targetDate": "20 Dec 2026",
    "area": "6 stages"
  },
  {
    "id": "MH-NGP-2026-018",
    "name": "Nagpur Metro Reach 3 Extension",
    "district": "Nagpur",
    "department": "Urban Development",
    "state": "Maharashtra",
    "stage": "Section 15 objection review",
    "progress": 40,
    "probability": 0.31105,
    "expectedDelay": 24,
    "risk": "MEDIUM",
    "factor": "Documents awaiting verification",
    "updated": "9 days ago",
    "parcels": 97,
    "owners": 148,
    "objections": 12,
    "compensation": "₹12.9 Cr pending",
    "legal": "No active cases",
    "targetDate": "13 Feb 2027",
    "area": "5 stages"
  },
  {
    "id": "RJ-JAI-2026-026",
    "name": "Jaipur Outer Ring Road Package 6",
    "district": "Jaipur",
    "department": "National Highways Authority",
    "state": "Rajasthan",
    "stage": "Section 15 objection review",
    "progress": 40,
    "probability": 0.38912,
    "expectedDelay": 26,
    "risk": "MEDIUM",
    "factor": "Unresolved landowner objections",
    "updated": "5 days ago",
    "parcels": 241,
    "owners": 316,
    "objections": 58,
    "compensation": "₹24.7 Cr pending",
    "legal": "No active cases",
    "targetDate": "24 Jan 2027",
    "area": "5 stages"
  },
  {
    "id": "MP-BPL-2026-012",
    "name": "Bhopal Water Grid Feeder Canal",
    "district": "Bhopal",
    "department": "Water Resources",
    "state": "Madhya Pradesh",
    "stage": "Section 23 award preparation",
    "progress": 60,
    "probability": 0.34356,
    "expectedDelay": 23,
    "risk": "MEDIUM",
    "factor": "Compensation ageing in processing",
    "updated": "7 days ago",
    "parcels": 128,
    "owners": 174,
    "objections": 21,
    "compensation": "₹14.4 Cr pending",
    "legal": "No active cases",
    "targetDate": "28 Feb 2027",
    "area": "5 stages"
  },
  {
    "id": "AP-VJA-2026-019",
    "name": "Vijayawada Industrial Access Corridor",
    "district": "NTR",
    "department": "Industrial Development",
    "state": "Andhra Pradesh",
    "stage": "Section 19 declaration",
    "progress": 60,
    "probability": 0.35662,
    "expectedDelay": 30,
    "risk": "MEDIUM",
    "factor": "Stage older than its baseline",
    "updated": "11 days ago",
    "parcels": 163,
    "owners": 221,
    "objections": 13,
    "compensation": "₹19.8 Cr pending",
    "legal": "No active cases",
    "targetDate": "04 Jan 2027",
    "area": "5 stages"
  },
  {
    "id": "GJ-RJT-2026-028",
    "name": "Rajkot Eastern Bypass",
    "district": "Rajkot",
    "department": "Public Works Department",
    "state": "Gujarat",
    "stage": "Survey and demarcation",
    "progress": 25,
    "probability": 0.4207,
    "expectedDelay": 35,
    "risk": "MEDIUM",
    "factor": "Required documents missing",
    "updated": "8 days ago",
    "parcels": 112,
    "owners": 143,
    "objections": 8,
    "compensation": "₹8.8 Cr pending",
    "legal": "No active cases",
    "targetDate": "08 Feb 2027",
    "area": "4 stages"
  },
  {
    "id": "AS-KAM-2026-005",
    "name": "Guwahati Railway Over Bridge Approach",
    "district": "Kamrup Metropolitan",
    "department": "Railways",
    "state": "Assam",
    "stage": "Section 15 objection review",
    "progress": 50,
    "probability": 0.37829,
    "expectedDelay": 25,
    "risk": "MEDIUM",
    "factor": "Unresolved ownership records",
    "updated": "13 days ago",
    "parcels": 47,
    "owners": 71,
    "objections": 7,
    "compensation": "₹5.2 Cr pending",
    "legal": "No active cases",
    "targetDate": "10 Mar 2027",
    "area": "4 stages"
  },
  {
    "id": "PB-ASR-2026-003",
    "name": "Amritsar-Jalandhar Expressway Package 3",
    "district": "Amritsar",
    "department": "National Highways Authority",
    "state": "Punjab",
    "stage": "Compensation disbursement",
    "progress": 71,
    "probability": 0.745,
    "expectedDelay": 68,
    "risk": "HIGH",
    "factor": "Unresolved ownership records",
    "updated": "9 days ago",
    "parcels": 287,
    "owners": 394,
    "objections": 47,
    "compensation": "₹63.4 Cr pending",
    "legal": "2 open matters",
    "targetDate": "26 Oct 2026",
    "area": "7 stages"
  },
  {
    "id": "MH-PUN-2026-011",
    "name": "Pune Outer Ring Road Package 7",
    "district": "Pune",
    "department": "Public Works Department",
    "state": "Maharashtra",
    "stage": "Section 15 objection review",
    "progress": 40,
    "probability": 0.7279,
    "expectedDelay": 67,
    "risk": "HIGH",
    "factor": "Current milestone overdue",
    "updated": "14 days ago",
    "parcels": 231,
    "owners": 312,
    "objections": 68,
    "compensation": "₹49.8 Cr pending",
    "legal": "1 open matter",
    "targetDate": "25 Nov 2026",
    "area": "5 stages"
  },
  {
    "id": "TN-CHN-2026-016",
    "name": "Chennai Peripheral Logistics Hub",
    "district": "Chengalpattu",
    "department": "Industrial Development",
    "state": "Tamil Nadu",
    "stage": "Compensation disbursement",
    "progress": 67,
    "probability": 0.74774,
    "expectedDelay": 74,
    "risk": "HIGH",
    "factor": "Current milestone overdue",
    "updated": "12 days ago",
    "parcels": 198,
    "owners": 246,
    "objections": 26,
    "compensation": "₹72.2 Cr pending",
    "legal": "1 open matter",
    "targetDate": "10 Nov 2026",
    "area": "6 stages"
  },
  {
    "id": "UP-KNP-2026-021",
    "name": "Kanpur Defence Corridor Link Road",
    "district": "Kanpur Nagar",
    "department": "Industrial Development",
    "state": "Uttar Pradesh",
    "stage": "Section 23 award preparation",
    "progress": 67,
    "probability": 0.71224,
    "expectedDelay": 68,
    "risk": "HIGH",
    "factor": "Stage older than its baseline",
    "updated": "26 days ago",
    "parcels": 216,
    "owners": 289,
    "objections": 33,
    "compensation": "₹51.3 Cr pending",
    "legal": "1 open matter",
    "targetDate": "20 Nov 2026",
    "area": "6 stages"
  },
  {
    "id": "MH-NSK-2026-024",
    "name": "Nashik-Sinnar Industrial Corridor",
    "district": "Nashik",
    "department": "Industrial Development",
    "state": "Maharashtra",
    "stage": "Section 19 declaration",
    "progress": 60,
    "probability": 0.7434,
    "expectedDelay": 66,
    "risk": "HIGH",
    "factor": "Required documents missing",
    "updated": "16 days ago",
    "parcels": 187,
    "owners": 234,
    "objections": 62,
    "compensation": "₹36.8 Cr pending",
    "legal": "No active cases",
    "targetDate": "05 Dec 2026",
    "area": "5 stages"
  },
  {
    "id": "BR-PAT-2026-013",
    "name": "Patna Ganga Path Eastern Extension",
    "district": "Patna",
    "department": "Urban Development",
    "state": "Bihar",
    "stage": "Section 23 award preparation",
    "progress": 67,
    "probability": 0.63437,
    "expectedDelay": 52,
    "risk": "HIGH",
    "factor": "Open legal cases",
    "updated": "8 days ago",
    "parcels": 142,
    "owners": 198,
    "objections": 31,
    "compensation": "₹28.9 Cr pending",
    "legal": "3 open matters",
    "targetDate": "05 Nov 2026",
    "area": "6 stages"
  },
  {
    "id": "MP-IDR-2026-027",
    "name": "Indore Metro Depot Land Assembly",
    "district": "Indore",
    "department": "Urban Development",
    "state": "Madhya Pradesh",
    "stage": "Section 15 objection review",
    "progress": 50,
    "probability": 0.74987,
    "expectedDelay": 61,
    "risk": "HIGH",
    "factor": "Unresolved ownership records",
    "updated": "10 days ago",
    "parcels": 94,
    "owners": 161,
    "objections": 33,
    "compensation": "₹21.5 Cr pending",
    "legal": "1 open matter",
    "targetDate": "10 Dec 2026",
    "area": "4 stages"
  },
  {
    "id": "KA-DWD-2026-030",
    "name": "Hubballi-Ankola Railway Link Section 2",
    "district": "Dharwad",
    "department": "Railways",
    "state": "Karnataka",
    "stage": "Section 19 declaration",
    "progress": 60,
    "probability": 0.74366,
    "expectedDelay": 64,
    "risk": "HIGH",
    "factor": "Stage older than its baseline",
    "updated": "19 days ago",
    "parcels": 176,
    "owners": 218,
    "objections": 41,
    "compensation": "₹33.1 Cr pending",
    "legal": "No active cases",
    "targetDate": "15 Dec 2026",
    "area": "5 stages"
  },
  {
    "id": "MH-MUM-2026-002",
    "name": "Mumbai Coastal Freight Corridor Package 2",
    "district": "Mumbai Suburban",
    "department": "Urban Development",
    "state": "Maharashtra",
    "stage": "Section 15 objection review",
    "progress": 33,
    "probability": 0.93396,
    "expectedDelay": 98,
    "risk": "CRITICAL",
    "factor": "Open legal cases",
    "updated": "21 days ago",
    "parcels": 264,
    "owners": 487,
    "objections": 218,
    "compensation": "₹128.4 Cr pending",
    "legal": "6 open matters",
    "targetDate": "02 Aug 2026",
    "area": "6 stages"
  },
  {
    "id": "HR-GGN-2026-004",
    "name": "Gurugram-Sohna Elevated Corridor",
    "district": "Gurugram",
    "department": "National Highways Authority",
    "state": "Haryana",
    "stage": "Section 19 declaration",
    "progress": 60,
    "probability": 0.9,
    "expectedDelay": 96,
    "risk": "CRITICAL",
    "factor": "Active stay order",
    "updated": "15 days ago",
    "parcels": 152,
    "owners": 241,
    "objections": 76,
    "compensation": "₹64.3 Cr pending",
    "legal": "Stay order in force",
    "targetDate": "06 Sep 2026",
    "area": "5 stages"
  },
  {
    "id": "UP-VNS-2026-006",
    "name": "Varanasi Ring Road Phase III",
    "district": "Varanasi",
    "department": "National Highways Authority",
    "state": "Uttar Pradesh",
    "stage": "Section 23 award preparation",
    "progress": 67,
    "probability": 0.92183,
    "expectedDelay": 97,
    "risk": "CRITICAL",
    "factor": "Open legal cases",
    "updated": "28 days ago",
    "parcels": 312,
    "owners": 428,
    "objections": 147,
    "compensation": "₹161.2 Cr pending",
    "legal": "5 open matters",
    "targetDate": "08 Jul 2026",
    "area": "6 stages"
  }
];

export const trend: DashboardData['trend'] = [
  {
    "month": "Apr",
    "probability": 0.319,
    "critical": 0,
    "high": 3
  },
  {
    "month": "May",
    "probability": 0.35,
    "critical": 0,
    "high": 3
  },
  {
    "month": "Jun",
    "probability": 0.375,
    "critical": 0,
    "high": 10
  },
  {
    "month": "Jul",
    "probability": 0.411,
    "critical": 2,
    "high": 8
  },
  {
    "month": "Aug",
    "probability": 0.451,
    "critical": 2,
    "high": 9
  },
  {
    "month": "Sep",
    "probability": 0.493,
    "critical": 3,
    "high": 8
  }
];

export const districts: DashboardData['districts'] = [
  {
    "name": "Mumbai Suburban",
    "state": "Maharashtra",
    "value": 93,
    "projects": 1
  },
  {
    "name": "Varanasi",
    "state": "Uttar Pradesh",
    "value": 92,
    "projects": 1
  },
  {
    "name": "Gurugram",
    "state": "Haryana",
    "value": 90,
    "projects": 1
  },
  {
    "name": "Amritsar",
    "state": "Punjab",
    "value": 75,
    "projects": 1
  },
  {
    "name": "Chengalpattu",
    "state": "Tamil Nadu",
    "value": 75,
    "projects": 1
  },
  {
    "name": "Indore",
    "state": "Madhya Pradesh",
    "value": 75,
    "projects": 1
  },
  {
    "name": "Dharwad",
    "state": "Karnataka",
    "value": 74,
    "projects": 1
  },
  {
    "name": "Pune",
    "state": "Maharashtra",
    "value": 73,
    "projects": 1
  },
  {
    "name": "Kanpur Nagar",
    "state": "Uttar Pradesh",
    "value": 71,
    "projects": 1
  },
  {
    "name": "Patna",
    "state": "Bihar",
    "value": 63,
    "projects": 1
  },
  {
    "name": "Rajkot",
    "state": "Gujarat",
    "value": 42,
    "projects": 1
  },
  {
    "name": "Nashik",
    "state": "Maharashtra",
    "value": 40,
    "projects": 2
  }
];
